server.port: 8081

spring:
  kafka:
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password:
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect




