version: "3"

services:
  consumer:
    build: ./consumer-service
    ports:
      - "8080:8080"
  producer:
    build: ./producer-service
    ports:
      - "8081:8081"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
  db:
    image: 'postgres:13'
    container_name: 'postgres13'
    restart: always
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'
    ports:
      - "5432:5432"